alias: OpenEPaperLink_Bambulabs_a1_mini
description: Bambulabs A1 Mini 2.66 Anzeige
trigger:
  - platform: time_pattern
    hours: /3
condition:
  - condition: time
    after: "06:00:00"
    before: "20:00:00"
    weekday:
      - sat
      - fri
      - thu
      - wed
      - tue
      - mon
      - sun
action:
  - service: open_epaper_link.drawcustom
    target:
    device_id:
    - 50ebc52fa9ec1ef69ad86ccf6ce8140a
data:
  rotate: 0
  dither: 2
  ttl: 60
  dry-run: false
  background: white
  payload:
    - type: dlimg
      url: /media/bambu-lab.png
      x: 0
      "y": 0
      xsize: 36
      ysize: 36
      rotate: 0
    - type: text
      value: A1mini
      font: ppb.ttf
      x: 40
      "y": 10
      size: 15
    - type: progress_bar
      x_start: 100
      y_start: 5
      x_end: 220
      y_end: 25
      fill: b
      outline: black
      width: 1
      progress: >-
        {{ states('sensor.a1mini_0309da3b0700269_druckfortschritt') | round |
        int(0) }}
      show_percentage: true
    - type: icon
      value: >-
        {% set druckerstatus =
        states('sensor.a1mini_0309da3b0700269_druckstatus') | string %} {% if
        druckerstatus == 'failed' %}
          printer-pos-alert-outline
        {% elif druckerstatus == 'finish' %}
          printer-pos-check-outline
        {% elif druckerstatus == 'idle' %}
          printer-pos-refresh-outline
        {% elif druckerstatus == 'init' %}
          cloud-print-outline
        {% elif druckerstatus == 'offline' %}
          printer-off-outline
        {% elif druckerstatus == 'pause' %}
          printer-pos-pause-outline
        {% elif druckerstatus == 'prepare' %}
          printer-pos-edit-outline
        {% elif druckerstatus == 'running' %}
          printer-pos-play-outline
        {% else %}
           sync-alert
        {% endif %}
      x: 230
      "y": 10
      size: 15
      color: black
    - type: text
      value: >-
        {{states('sensor.000003350d5f3e1e_last_seen') | as_timestamp() |
        timestamp_custom('%H:%M')}}
      font: ppb.ttf
      x: 250
      "y": 15
      size: 12
      color: red
    - type: line
      x_start: 0
      x_end: 290
      y_start: 31
      y_end: 31
      width: 1
      fill: black
    - type: text
      value: Schicht
      font: ppb.ttf
      x: 30
      "y": 35
      size: 14
    - type: text
      value: Aktuell
      font: ppb.ttf
      x: 30
      "y": 60
      size: 14
    - type: text
      value: Düse
      font: ppb.ttf
      x: 30
      "y": 85
      size: 14
    - type: text
      value: Bett
      font: ppb.ttf
      x: 30
      "y": 110
      size: 14
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_gesamtzahl_der_schichten') |
        round | int(0)}}
      font: ppb.ttf
      x: 100
      "y": 35
      size: 14
      color: red
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_aktuelle_schicht') | round |
        int(0)}}
      font: ppb.ttf
      x: 100
      "y": 60
      size: 14
      color: red
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_temperatur_der_duse') | round |
        int(0)}}°C
      font: ppb.ttf
      x: 100
      "y": 85
      size: 14
      color: red
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_druckbetttemperatur') | round |
        int(0)}}°C
      font: ppb.ttf
      x: 100
      "y": 110
      size: 14
      color: red
    - type: icon_sequence
      x: 10
      "y": 30
      icons:
        - mdi:priority-high
        - mdi:printer-3d-nozzle
        - mdi:printer-3d-nozzle-heat-outline
        - mdi:printer-3d-nozzle-heat
      size: 20
      direction: down
    - type: text
      value: Hotend
      font: ppb.ttf
      x: 175
      "y": 35
      size: 14
    - type: text
      value: Bauteil
      font: ppb.ttf
      x: 175
      "y": 60
      size: 14
    - type: text
      value: Fil.Gew.
      font: ppb.ttf
      x: 175
      "y": 85
      size: 14
    - type: text
      value: Druckzeit
      font: ppb.ttf
      x: 175
      "y": 110
      size: 14
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_hotendlufterdrehzahl') | round |
        int(0)}}%
      font: ppb.ttf
      x: 235
      "y": 35
      size: 14
      color: red
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_druckkopflufterdrehzahl') |
        round | int(0)}}%
      font: ppb.ttf
      x: 235
      "y": 60
      size: 14
      color: red
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_gewicht_des_drucks') | round |
        int(0)}}gr
      font: ppb.ttf
      x: 235
      "y": 85
      size: 14
      color: red
    - type: text
      value: >-
        {{states('sensor.a1mini_0309da3b0700269_verbleibende_zeit') | round |
        int(0)}}min
      font: ppb.ttf
      x: 245
      "y": 110
      size: 14
      color: red
    - type: icon_sequence
      x: 150
      "y": 30
      icons:
        - mdi:hvac
        - mdi:turbine
        - mdi:weight-gram
        - mdi:timeline
      size: 20
      direction: down
    - type: text
      value: >-
        {% set value = states('sensor.a1mini_0309da3b0700269_name_der_aufgabe')
        %} {{ value if value not in [None, '', 'unknown', 'unavailable'] else
        'Druckdateiname' }}
      font: ppb.ttf
      x: 5
      "y": 130
      size: 12
mode: single
