- platform: template
  sensors:
    flightradar24_current_flight_number:
      friendly_name: "Aktueller Flug"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].flight_number }}
        {% else %}
          Unbekannt
        {% endif %}
    flightradar24_current_flight_aircraft_registration:
      friendly_name: "Flugzeug Register"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].aircraft_registration }}
        {% endif %}
    flightradar24_current_flight_airport_origin_country_code:
      friendly_name: "Flughafen(Abflugcode)"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].airport_origin_country_code }}
        {% endif %}
    flightradar24_current_flight_airport_destination_country_code:
      friendly_name: "Flughafen(Zielflugcode)"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].airport_destination_country_code }}
        {% endif %}
    flightradar24_current_flight_airport_origin_city:
      friendly_name: "Flughafen(Abflugcode)"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].airport_origin_city }}
        {% else %}
          Unbekannt
        {% endif %}
    flightradar24_current_flight_airport_destination_city:
      friendly_name: "Flughafen(Zielflugcode)"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].airport_destination_city }}
        {% else %}
          Unbekannt
        {% endif %}
    flightradar24_current_flight_time_scheduled_departure:
      friendly_name: "Abflug"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].time_scheduled_departure | timestamp_custom('%H:%M') }}
        {% else %}
          00:00
        {% endif %}
    flightradar24_current_flight_time_scheduled_arrival:
      friendly_name: "Ankunfszeit"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].time_scheduled_arrival | timestamp_custom('%H:%M') }}
        {% else %}
          00:00
        {% endif %}
    flightradar24_current_flight_aircraft_model:
      friendly_name: "Typ"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].aircraft_model }}
        {% else %}
          Keine Daten
        {% endif %}
    flightradar24_current_flight_airline_short:
      friendly_name: "Fluglinie Kurzbez"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].airline_short }}
        {% endif %}
    flightradar24_current_airline_short:
      friendly_name: "Flugzeugname (kurz)"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights[0].airline_short }}
        {% endif %}
    flightradar24_current_in_area:
      friendly_name: "In Region"
      value_template: >-
        {% set flights = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
        {% if flights %}
          {{ flights }}
        {% else %}
          0
        {% endif %}

    cape:
      friendly_name: "CAPE"
      value_template: >-
        {% set t = states('sensor.nuernberg_temperatur') | float %}
        {% set td = states('sensor.nuernberg_taupunkt') | float %}
        {% set p = states('sensor.nuernberg_druck') | float %}
        {% set cape = (t - td) * 0.5 * p %} 
        {{ cape | round(2) }}
    lifted_index:
      friendly_name: "Lifted Index"
      value_template: >-
        {% set t = states('sensor.nuernberg_temperatur') | float %}
        {% set td = states('sensor.nuernberg_taupunkt') | float %}
        {% set p = states('sensor.nuernberg_druck') | float %}
        {% set li = t - (td * 0.5) %} 
        {{ li | round(2) }}
