alias: OpenEPaperlink_Muell_Mini
description: Müllkalender Mini 1.54
trigger:
  - platform: time_pattern
    hours: /6
condition:
  - condition: time
    after: "06:00:00"
    before: "20:00:00"
    weekday:
      - sat
      - fri
      - thu
      - wed
      - tue
      - mon
      - sun
action:
  - service: open_epaper_link.drawcustom
    target:
      entity_id:
        - open_epaper_link.0000021EEE5D3413
    data:
      background: white
      rotate: 0
      payload:
        - type: icon
          value: calendar-clock-outline
          x: 2
          "y": 100
          size: 40
          color: red
        - type: text
          value: "{{ 'Abh.:' + states('sensor.abfallnaechster') }}"
          font: ppb.ttf
          x: 22
          "y": 2
          size: 14
          color: red
        - type: icon
          value: truck-cargo-container
          x: 100
          "y": 100
          size: 40
          color: red
        - type: text
          value: Biotonne
          font: ppb.ttf
          x: 5
          "y": 20
          size: 12
        - type: text
          value: "{{ states('sensor.bioabfall') }}"
          font: ppb.ttf
          x: 10
          "y": 70
          size: 12
        - type: icon
          value: >
            {% set bioabfall_wert = states('sensor.bioabfall') | string %} {% if
            bioabfall_wert == '1 Taeg' %}
              delete-alert-outline
            {% elif bioabfall_wert == '2 Tage' %}
              delete-clock-outline
            {% elif bioabfall_wert == '3 Tage' %}
              delete-empty-outline
            {% elif bioabfall_wert == '4 Tage' %}
              delete-variant
            {% elif bioabfall_wert == '5 Tage' %}
              delete-outline
            {% else %}
               delete-sweep-outline
            {% endif %}                  
          x: 20
          "y": 30
          size: 40
          color: black
        - type: text
          value: Gelber Sack
          font: ppb.ttf
          x: 70
          "y": 20
          size: 12
        - type: text
          value: "{{ states('sensor.gelbetonne') }}"
          font: ppb.ttf
          x: 90
          "y": 70
          size: 12
        - type: icon
          value: >
            {% set gelbetonne_wert = states('sensor.gelbetonne') | string %} {%
            if gelbetonne_wert == '1 Tage' %}
              delete-alert-outline
            {% elif gelbetonne_wert == '2 Tage' %}
              delete-clock-outline
            {% elif gelbetonne_wert == '3 Tage' %}
              delete-empty-outline
            {% elif gelbetonne_wert == '4 Tage' %}
              delete-variant
            {% elif gelbetonne_wert == '5 Tage' %}
              delete-outline
            {% else %}
               delete-sweep-outline
            {% endif %}                  
          x: 95
          "y": 30
          size: 40
          color: black
        - type: text
          value: Restmüll
          font: ppb.ttf
          x: 40
          "y": 83
          size: 12
        - type: text
          value: "{{ states('sensor.restabfall') }}"
          font: ppb.ttf
          x: 50
          "y": 140
          size: 12
        - type: icon
          value: >
            {% set restabfall_wert = states('sensor.restabfall') | string %} {%
            if restabfall_wert == '1 Tage' %}
              delete-alert-outline
            {% elif restabfall_wert == '2 Tage' %}
              delete-clock-outline
            {% elif restabfall_wert == '3 Tage' %}
              delete-empty-outline
            {% elif restabfall_wert == '4 Tage' %}
              delete-variant
            {% elif restabfall_wert == '5 Tage' %}
              delete-outline
            {% else %}
               delete-sweep-outline
            {% endif %}                  
          x: 50
          "y": 95
          size: 40
          color: black
mode: single
