alias: OpenEpaperLink_SolarRainAlert_Mini
description: Zigbee Solar Regenmelder V2
triggers:
  - hours: /3
    trigger: time_pattern
conditions:
  - condition: time
    after: "06:00:00"
    before: "20:00:00"
    weekday:
      - sat
      - fri
      - thu
      - wed
      - tue
      - mon
      - sun
actions:
  - target:
      device_id:
        - 9212ba30896458119fbc5fea2e5bcec9
    data:
      rotate: 0
      dither: 2
      ttl: 60
      dry-run: false
      payload:
        - type: icon
          value: weather-rainy
          x: 125
          "y": 0
          size: 20
          color: black
        - type: text
          value: "{{ 'Solar Regen' }}"
          font: ppb.ttf
          x: 10
          "y": 2
          size: 14
          color: red
        - type: dlimg
          url: /media/solar_rain_sensor.jpg
          x: 12
          "y": 20
          xsize: 80
          ysize: 80
          rotate: 0
        - type: text
          value: >-
            {% set wahrnung = states('binary_sensor.tz3210_tgvtvdoc_ts0207') |
            string %}  {% if wahrnung == 'off' %}
               Kein Regen
             {% else %}
               Regen
             {% endif %}
             
          font: ppb.ttf
          x: 20
          "y": 14
          size: 14
          color: red
        - type: icon
          value: >
            {{ 'weather-sunny' if
            is_state('binary_sensor.tz3210_tgvtvdoc_ts0207', 'off') else
            'weather-rainy' }}
          x: 100
          "y": 30
          size: 40
          color: >
            {{ 'black' if is_state('binary_sensor.tz3210_tgvtvdoc_ts0207',
            'off') else 'red' }}
        - type: text
          value: >
            {{
            state_attr('sensor.tz3210_tgvtvdoc_ts0207_batterie','battery_quantity')
            }}%
          font: ppb.ttf
          x: 100
          "y": 80
          size: 12
          color: red
        - type: icon
          value: >
            {% set batterystatus = 
            state_attr('sensor.tz3210_tgvtvdoc_ts0207_batterie','battery_quantity')
            | int(default=0) %} {% if batterystatus == 1 %}
              battery-100
            {% else %}
              battery-50
            {% endif %}
          x: 120
          "y": 70
          size: 20
          color: black
        - type: text
          value: >-
            {{
            "{:_.0f}".format(states('sensor.tz3210_tgvtvdoc_ts0207_beleuchtungsstarke')
            | int(default=0)) | replace('_', '.') }} lx
          x: 25
          "y": 110
          size: 15
          color: black
        - type: text
          value: >-
            {{
            "{:_.0f}".format(states('sensor.tz3210_tgvtvdoc_ts0207_beleuchtungsstarke_2')
            | int(default=0)) | replace('_', '.') }} lx
          x: 25
          "y": 132
          size: 15
          color: black
        - type: icon
          value: solar-power-variant-outline
          x: 10
          "y": 110
          size: 16
          color: black
        - type: icon
          value: solar-power-variant-outline
          x: 10
          "y": 130
          size: 16
          color: black
        - type: icon
          value: update
          x: 105
          "y": 110
          size: 20
          color: black
        - type: text
          value: >-
            {{ states('sensor.000002A9612A3418_last_seen') | as_timestamp() |
            timestamp_custom('%H:%M')}} Uhr
          font: ppb.ttf
          x: 90
          "y": 135
          size: 12
          color: red
    action: open_epaper_link.drawcustom
mode: single
